/**
 * Demo Registry — comprehensive visual demos for UI glossary terms.
 */

import { extras1 } from './extras-1.js'
import { extras2 } from './extras-2.js'
import { extras3 } from './extras-3.js'
import { extras4 } from './extras-4.js'

/* ── SVG helpers ────────────────────────────────────────────── */
const svg = (w, h, inner) => `<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${inner}</svg>`
const ico = (p) => svg(16, 16, p)

const I = Object.freeze({
  check: ico('<polyline points="4 8 7 11 12 5"/>'),
  chev: ico('<polyline points="4 6 8 10 12 6"/>'),
  close: ico('<line x1="4" y1="4" x2="12" y2="12"/><line x1="12" y1="4" x2="4" y2="12"/>'),
  search: ico('<circle cx="7" cy="7" r="4"/><line x1="10" y1="10" x2="14" y2="14"/>'),
  star: ico('<polygon points="8 1 10 6 15 6.5 11 10 12.5 15 8 12 3.5 15 5 10 1 6.5 6 6" fill="currentColor" stroke="none"/>'),
  starE: ico('<polygon points="8 1 10 6 15 6.5 11 10 12.5 15 8 12 3.5 15 5 10 1 6.5 6 6"/>'),
  ham: ico('<line x1="2" y1="4" x2="14" y2="4"/><line x1="2" y1="8" x2="14" y2="8"/><line x1="2" y1="12" x2="14" y2="12"/>'),
  plus: ico('<line x1="8" y1="3" x2="8" y2="13"/><line x1="3" y1="8" x2="13" y2="8"/>'),
  upload: ico('<polyline points="4 8 8 4 12 8"/><line x1="8" y1="4" x2="8" y2="13"/><line x1="3" y1="14" x2="13" y2="14"/>'),
  checkC: ico('<circle cx="8" cy="8" r="6"/><polyline points="5.5 8 7.5 10 10.5 6"/>'),
  lock: ico('<rect x="4" y="7" width="8" height="6" rx="1"/><path d="M6 7V5a2 2 0 0 1 4 0v2"/>'),
  cal: ico('<rect x="2" y="3" width="12" height="12" rx="1.5"/><line x1="2" y1="7" x2="14" y2="7"/><line x1="5" y1="1" x2="5" y2="4"/><line x1="11" y1="1" x2="11" y2="4"/>'),
  arrL: ico('<line x1="12" y1="8" x2="4" y2="8"/><polyline points="7 4 3 8 7 12"/>'),
  arrR: ico('<line x1="4" y1="8" x2="12" y2="8"/><polyline points="9 4 13 8 9 12"/>'),
  arrU: ico('<line x1="8" y1="13" x2="8" y2="3"/><polyline points="4 7 8 3 12 7"/>'),
  eye: ico('<path d="M1 8s3-5 7-5 7 5 7 5-3 5-7 5-7-5-7-5z"/><circle cx="8" cy="8" r="2"/>'),
  link: ico('<path d="M7 11l-1.5 1.5a2.12 2.12 0 0 1-3-3L5 8"/><path d="M9 5l1.5-1.5a2.12 2.12 0 0 1 3 3L11 8"/>'),
  bell: ico('<path d="M8 14c.6 0 1-.4 1-1H7c0 .6.4 1 1 1z"/><path d="M12 10V7a4 4 0 1 0-8 0v3l-1 2h10l-1-2z"/>'),
  gear: ico('<circle cx="8" cy="8" r="2.5"/><path d="M8 1.5v1.3M8 13.2v1.3M1.5 8h1.3M13.2 8h1.3M3.4 3.4l.9.9M11.7 11.7l.9.9M3.4 12.6l.9-.9M11.7 4.3l.9-.9"/>'),
  user: ico('<circle cx="8" cy="5" r="2.5"/><path d="M3 14c0-3 2.2-5 5-5s5 2 5 5"/>'),
  file: ico('<path d="M9 1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V5L9 1z"/><polyline points="9 1 9 5 13 5"/>'),
  code: ico('<polyline points="5 4 1 8 5 12"/><polyline points="11 4 15 8 11 12"/>'),
  layers: ico('<polygon points="8 1 15 5 8 9 1 5"/><polyline points="1 9 8 13 15 9"/>'),
})

const W = (inner) => `<div class="demo-wrapper">${inner}</div>`
const WS = (s, inner) => `<div class="demo-wrapper" style="${s}">${inner}</div>`

/* ── Hash for minimap variety ───────────────────────────────── */
const hash = (s) => { let h = 0; for (let i = 0; i < s.length; i++) { h = ((h << 5) - h + s.charCodeAt(i)) | 0 } return Math.abs(h) }

/* ── Term demos ─────────────────────────────────────────────── */
const specific = Object.freeze({
  // ── Buttons ──
  'button': () => W('<button class="demo-btn demo-btn-primary">Primary</button><button class="demo-btn demo-btn-secondary">Secondary</button><button class="demo-btn demo-btn-ghost">Ghost</button>'),
  'primary-button': () => W('<button class="demo-btn demo-btn-primary">Primary</button>'),
  'secondary-button': () => W('<button class="demo-btn demo-btn-secondary">Secondary</button>'),
  'tertiary-button': () => W('<button class="demo-btn demo-btn-ghost" style="border:none">Tertiary</button>'),
  'ghost-button': () => W('<button class="demo-btn demo-btn-ghost">Ghost</button>'),
  'text-button': () => W('<button style="background:none;border:none;color:#3b82f6;font-size:13px;font-weight:500;cursor:pointer;text-decoration:underline">Text Button</button>'),
  'toggle-button': () => W('<button class="demo-switch on" data-demo-toggle="switch"></button><span style="font-size:12px;color:var(--color-text-tertiary)">ON</span>'),
  'icon-button': () => W(`<button class="demo-btn-icon">${I.plus}</button><button class="demo-btn-icon">${I.search}</button><button class="demo-btn-icon">${I.close}</button>`),
  'floating-action-button-fab': () => W(`<button class="demo-btn-icon" style="width:48px;height:48px;background:#3b82f6;color:white;box-shadow:0 4px 14px rgba(59,130,246,0.4)">${I.plus}</button>`),
  'split-button': () => WS('gap:0', `<button class="demo-btn demo-btn-primary" style="border-radius:8px 0 0 8px">Save</button><button class="demo-btn demo-btn-primary" style="border-radius:0 8px 8px 0;padding:8px;border-left:1px solid rgba(255,255,255,0.25)">${I.chev}</button>`),
  'combo-button': () => WS('gap:0', `<button class="demo-btn demo-btn-primary" style="border-radius:8px 0 0 8px">Action</button><button class="demo-btn demo-btn-primary" style="border-radius:0 8px 8px 0;padding:8px;border-left:1px solid rgba(255,255,255,0.25)">${I.chev}</button>`),
  'close-button': () => W(`<button class="demo-btn-icon" style="background:var(--color-surface-hover)">${I.close}</button>`),
  'back-button': () => W(`<button class="demo-btn-icon" style="background:var(--color-surface-hover)">${I.arrL}</button>`),
  'submit-button': () => W('<button class="demo-btn demo-btn-primary">Submit</button>'),
  'reset-button': () => W('<button class="demo-btn demo-btn-ghost">Reset</button>'),
  'destructive-button': () => W('<button class="demo-btn demo-btn-destructive">Delete</button>'),
  'cta-call-to-action': () => W('<button class="demo-btn demo-btn-primary" style="padding:10px 28px;font-size:14px;font-weight:600;background:linear-gradient(135deg,#3b82f6,#8b5cf6);box-shadow:0 4px 14px rgba(59,130,246,0.35)">Get Started</button>'),
  'button-group': () => WS('gap:0', '<button class="demo-btn demo-btn-secondary" style="border-radius:8px 0 0 8px;border-right:0">Left</button><button class="demo-btn demo-btn-secondary" style="border-radius:0;border-right:0">Mid</button><button class="demo-btn demo-btn-secondary" style="border-radius:0 8px 8px 0">Right</button>'),
  'speed-dial': () => WS('flex-direction:column;gap:6px', `<button class="demo-btn-icon" style="width:32px;height:32px;background:#f3f4f6">${I.file}</button><button class="demo-btn-icon" style="width:32px;height:32px;background:#f3f4f6">${I.user}</button><button class="demo-btn-icon" style="width:44px;height:44px;background:#3b82f6;color:white;box-shadow:0 4px 14px rgba(59,130,246,0.35)">${I.plus}</button>`),
  'toolbar': () => W(`<div style="display:flex;gap:2px;padding:4px;background:var(--color-surface-hover);border-radius:8px"><button class="demo-btn-icon" style="width:28px;height:28px">${I.code}</button><button class="demo-btn-icon" style="width:28px;height:28px">${I.eye}</button><button class="demo-btn-icon" style="width:28px;height:28px">${I.gear}</button><div style="width:1px;background:var(--color-border);margin:2px 4px"></div><button class="demo-btn-icon" style="width:28px;height:28px">${I.search}</button></div>`),
  'action-bar': () => W(`<div style="display:flex;gap:6px;padding:6px 10px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:8px;align-items:center"><span style="font-size:10px;color:var(--color-text-tertiary)">3 selected</span><button class="demo-btn demo-btn-primary" style="padding:4px 10px;font-size:11px">Edit</button><button class="demo-btn demo-btn-destructive" style="padding:4px 10px;font-size:11px">Delete</button></div>`),

  // ── Form Inputs ──
  'text-input': () => W('<input class="demo-input" type="text" placeholder="Type here..." readonly>'),
  'text-field': () => W('<input class="demo-input" type="text" placeholder="Text field..." readonly>'),
  'checkbox': () => WS('flex-direction:column;align-items:flex-start;gap:6px', `<label class="demo-checkbox checked" data-demo-toggle="checkbox"><span class="demo-checkbox-box"><span class="demo-checkbox-check">${I.check}</span></span><span>Checked</span></label><label class="demo-checkbox" data-demo-toggle="checkbox"><span class="demo-checkbox-box"><span class="demo-checkbox-check">${I.check}</span></span><span>Unchecked</span></label>`),
  'radio-button': () => `<div class="demo-wrapper" style="flex-direction:column;align-items:flex-start;gap:6px" data-demo-radio-group><label class="demo-radio selected" data-demo-toggle="radio"><span class="demo-radio-circle"><span class="demo-radio-dot"></span></span><span>Option A</span></label><label class="demo-radio" data-demo-toggle="radio"><span class="demo-radio-circle"><span class="demo-radio-dot"></span></span><span>Option B</span></label></div>`,
  'radio-group': () => `<div class="demo-wrapper" style="flex-direction:column;align-items:flex-start;gap:6px" data-demo-radio-group><label class="demo-radio selected" data-demo-toggle="radio"><span class="demo-radio-circle"><span class="demo-radio-dot"></span></span><span>A</span></label><label class="demo-radio" data-demo-toggle="radio"><span class="demo-radio-circle"><span class="demo-radio-dot"></span></span><span>B</span></label><label class="demo-radio" data-demo-toggle="radio"><span class="demo-radio-circle"><span class="demo-radio-dot"></span></span><span>C</span></label></div>`,
  'switch': () => WS('gap:12px', '<button class="demo-switch on" data-demo-toggle="switch"></button><button class="demo-switch" data-demo-toggle="switch"></button>'),
  'toggle': () => WS('gap:12px', '<button class="demo-switch on" data-demo-toggle="switch"></button><button class="demo-switch" data-demo-toggle="switch"></button>'),
  'select': () => W(`<div class="demo-dropdown-mini" data-demo-toggle="dropdown"><div class="demo-dropdown-trigger">Select ${I.chev}</div><div class="demo-dropdown-list"><div class="demo-dropdown-option">Option 1</div><div class="demo-dropdown-option">Option 2</div><div class="demo-dropdown-option">Option 3</div></div></div>`),
  'dropdown': () => W(`<div class="demo-dropdown-mini" data-demo-toggle="dropdown"><div class="demo-dropdown-trigger">Choose ${I.chev}</div><div class="demo-dropdown-list"><div class="demo-dropdown-option">Apple</div><div class="demo-dropdown-option">Banana</div><div class="demo-dropdown-option">Cherry</div></div></div>`),
  'slider': () => W('<input class="demo-slider" type="range" min="0" max="100" value="60">'),
  'range-slider': () => W('<input class="demo-slider" type="range" min="0" max="100" value="60">'),
  'textarea': () => W('<div class="demo-input" style="width:180px;height:50px;font-size:11px;color:var(--color-text-tertiary);display:flex;align-items:flex-start;padding-top:8px">Write something...</div>'),
  'search-field': () => W(`<div style="position:relative;display:inline-flex;align-items:center"><span style="position:absolute;left:10px;color:#9ca3af">${I.search}</span><input class="demo-input" style="padding-left:32px" placeholder="Search..." readonly></div>`),
  'password-field': () => W(`<div style="position:relative;display:inline-flex;align-items:center"><span style="position:absolute;left:10px;color:#9ca3af">${I.lock}</span><input class="demo-input" style="padding-left:32px;letter-spacing:3px" value="\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022" readonly></div>`),
  'date-picker': () => W(`<div style="position:relative;display:inline-flex;align-items:center"><span style="position:absolute;left:10px;color:#9ca3af">${I.cal}</span><input class="demo-input" style="padding-left:32px" value="2026-05-17" readonly></div>`),
  'file-uploader': () => W(`<div style="width:180px;height:60px;border:2px dashed #d1d5db;border-radius:8px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;color:#9ca3af;font-size:11px;cursor:pointer">${I.upload}<span>Drop files here</span></div>`),
  'combobox': () => W(`<div style="position:relative;display:inline-flex;align-items:center"><input class="demo-input" placeholder="Type to filter..." readonly><span style="position:absolute;right:10px;color:#9ca3af">${I.chev}</span></div>`),
  'tag-input': () => W(`<div style="display:flex;align-items:center;gap:4px;padding:4px 8px;border:1.5px solid #d1d5db;border-radius:8px;background:var(--color-surface);min-width:160px;flex-wrap:wrap"><span class="demo-chip" style="font-size:11px;padding:2px 8px">React</span><span class="demo-chip" style="font-size:11px;padding:2px 8px">Vue</span><span style="font-size:11px;color:#9ca3af">add...</span></div>`),
  'rating-control': () => { const f = Array(3).fill(`<span style="color:#f59e0b">${I.star}</span>`).join(''); const e = Array(2).fill(`<span style="color:#d1d5db">${I.starE}</span>`).join(''); return W(f + e) },
  'otp-input': () => WS('gap:6px', ['3','8','7',''].map(v => `<div style="width:32px;height:38px;border:1.5px solid ${v ? '#3b82f6' : '#d1d5db'};border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:16px;font-weight:600;color:var(--color-text-primary)">${v}</div>`).join('')),
  'placeholder': () => W('<input class="demo-input" style="color:#9ca3af" value="Placeholder text..." readonly>'),
  'label': () => WS('flex-direction:column;align-items:flex-start;gap:4px', '<label style="font-size:11px;font-weight:600;color:var(--color-text-primary)">Email</label><input class="demo-input" style="width:160px" placeholder="you@example.com" readonly>'),
  'floating-label': () => W('<div style="position:relative;width:160px"><label style="position:absolute;top:4px;left:12px;font-size:9px;color:#3b82f6;font-weight:500">Email</label><input class="demo-input" style="width:100%;padding-top:14px;border-color:#3b82f6;box-shadow:0 0 0 3px rgba(59,130,246,0.1)" value="user@mail.com" readonly></div>'),
  'helper-text': () => WS('flex-direction:column;align-items:flex-start;gap:3px', '<input class="demo-input" style="width:160px" placeholder="Password" readonly><span style="font-size:10px;color:var(--color-text-tertiary)">Must be 8+ characters</span>'),
  'required-indicator': () => WS('flex-direction:column;align-items:flex-start;gap:4px', '<label style="font-size:11px;font-weight:600">Name <span style="color:#ef4444">*</span></label><input class="demo-input" style="width:160px" readonly>'),
  'inline-validation': () => WS('flex-direction:column;gap:4px', '<input class="demo-input" style="border-color:#ef4444;box-shadow:0 0 0 3px rgba(239,68,68,0.1);width:160px" value="bad@" readonly><span style="font-size:10px;color:#ef4444">Invalid email</span>'),
  'error-message': () => W('<div style="display:flex;align-items:center;gap:6px;padding:6px 10px;background:#fef2f2;border:1px solid #fecaca;border-radius:6px;font-size:11px;color:#991b1b">' + I.close + ' Error occurred</div>'),
  'success-message': () => W('<div style="display:flex;align-items:center;gap:6px;padding:6px 10px;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:6px;font-size:11px;color:#166534">' + I.checkC + ' Saved!</div>'),
  'character-counter': () => WS('flex-direction:column;align-items:flex-end;gap:3px', '<input class="demo-input" style="width:160px" value="Hello world" readonly><span style="font-size:10px;color:var(--color-text-tertiary)">11 / 100</span>'),
  'color-picker': () => WS('gap:4px', ['#ef4444','#f59e0b','#22c55e','#3b82f6','#8b5cf6','#ec4899'].map(c => `<div style="width:24px;height:24px;border-radius:6px;background:${c};cursor:pointer;border:2px solid transparent;${c === '#3b82f6' ? 'border-color:#1d4ed8;box-shadow:0 0 0 2px rgba(59,130,246,0.3)' : ''}"></div>`).join('')),
  'number-input': () => WS('gap:0', `<button class="demo-btn-icon" style="width:30px;height:30px;border:1.5px solid #d1d5db;border-radius:8px 0 0 8px;border-right:0">-</button><div style="width:50px;height:30px;border:1.5px solid #d1d5db;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:500">42</div><button class="demo-btn-icon" style="width:30px;height:30px;border:1.5px solid #d1d5db;border-radius:0 8px 8px 0;border-left:0">+</button>`),
  'spinbutton': () => WS('gap:0', `<button class="demo-btn-icon" style="width:30px;height:30px;border:1.5px solid #d1d5db;border-radius:8px 0 0 8px;border-right:0">-</button><div style="width:50px;height:30px;border:1.5px solid #d1d5db;display:flex;align-items:center;justify-content:center;font-size:13px">7</div><button class="demo-btn-icon" style="width:30px;height:30px;border:1.5px solid #d1d5db;border-radius:0 8px 8px 0;border-left:0">+</button>`),
  'stepper-input': () => WS('gap:0', `<button class="demo-btn-icon" style="width:30px;height:30px;border:1.5px solid #d1d5db;border-radius:8px 0 0 8px;border-right:0">-</button><div style="width:50px;height:30px;border:1.5px solid #d1d5db;display:flex;align-items:center;justify-content:center;font-size:13px">5</div><button class="demo-btn-icon" style="width:30px;height:30px;border:1.5px solid #d1d5db;border-radius:0 8px 8px 0;border-left:0">+</button>`),
  'masked-input': () => W('<input class="demo-input" style="letter-spacing:2px" value="(090) 1234-5678" readonly>'),
  'captcha': () => W('<div style="padding:8px 12px;background:#f9fafb;border:1px solid #d1d5db;border-radius:6px;display:flex;align-items:center;gap:8px;font-size:11px"><div style="width:18px;height:18px;border:2px solid #d1d5db;border-radius:4px"></div><span>I\'m not a robot</span><div style="width:24px;height:24px;opacity:0.4">' + svg(24, 24, '<path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>') + '</div></div>'),

  // ── Navigation ──
  'breadcrumb': () => W('<nav class="demo-breadcrumb"><span class="demo-breadcrumb-item">Home</span><span class="demo-breadcrumb-sep">/</span><span class="demo-breadcrumb-item">Products</span><span class="demo-breadcrumb-sep">/</span><span class="demo-breadcrumb-item current">Detail</span></nav>'),
  'tab': () => W('<nav class="demo-tabs"><span class="demo-tab active">Tab 1</span><span class="demo-tab">Tab 2</span><span class="demo-tab">Tab 3</span></nav>'),
  'tab-bar': () => W(`<div style="display:flex;justify-content:space-around;padding:6px 12px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:10px;min-width:180px"><div style="display:flex;flex-direction:column;align-items:center;gap:2px;color:#3b82f6;font-size:9px">${I.layers}<span>Home</span></div><div style="display:flex;flex-direction:column;align-items:center;gap:2px;color:var(--color-text-tertiary);font-size:9px">${I.search}<span>Search</span></div><div style="display:flex;flex-direction:column;align-items:center;gap:2px;color:var(--color-text-tertiary);font-size:9px">${I.user}<span>Profile</span></div></div>`),
  'pagination': () => W(`<nav class="demo-pagination"><span class="demo-page-btn">${I.arrL}</span><span class="demo-page-btn">1</span><span class="demo-page-btn active">2</span><span class="demo-page-btn">3</span><span class="demo-page-btn">${I.arrR}</span></nav>`),
  'hamburger-menu': () => W(`<button class="demo-btn-icon" style="width:40px;height:40px">${I.ham}</button>`),
  'sidebar': () => W('<div class="demo-layout"><div class="demo-layout-sidebar" style="flex-direction:column;gap:6px;padding:6px 0"><div style="width:16px;height:2px;background:var(--color-text-tertiary);border-radius:1px"></div><div style="width:16px;height:2px;background:#3b82f6;border-radius:1px"></div><div style="width:16px;height:2px;background:var(--color-text-tertiary);border-radius:1px"></div></div><div class="demo-layout-main"><div class="demo-layout-header"></div><div class="demo-layout-body">Content</div></div></div>'),
  'drawer': () => W('<div style="width:160px;height:70px;border:1.5px solid var(--color-border);border-radius:6px;position:relative;overflow:hidden"><div style="position:absolute;top:0;right:0;width:55%;height:100%;background:var(--color-surface);border-left:1px solid var(--color-border);box-shadow:-2px 0 8px rgba(0,0,0,0.08);display:flex;align-items:center;justify-content:center;font-size:10px;color:var(--color-text-tertiary)">Drawer</div><div style="position:absolute;top:0;left:0;width:40%;height:100%;display:flex;align-items:center;justify-content:center;font-size:9px;color:var(--color-text-tertiary);opacity:0.5">Page</div></div>'),
  'stepper-navigation': () => { const steps = [1,2,3].map((n,i) => { const bg = i<=1?'#3b82f6':'#d1d5db'; const c = i<=1?'white':'#6b7280'; const ct = i===0?I.check:n; const line = i<2?`<div style="width:24px;height:2px;background:${i===0?'#3b82f6':'#d1d5db'}"></div>`:'' ; return `<div style="width:24px;height:24px;border-radius:50%;background:${bg};color:${c};display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:600">${ct}</div>${line}` }).join(''); return WS('gap:0', steps) },
  'segmented-control': () => W('<div style="display:flex;background:var(--color-surface-hover);border-radius:8px;padding:3px;gap:2px"><div style="padding:5px 14px;border-radius:6px;background:var(--color-surface);font-size:12px;font-weight:500;box-shadow:0 1px 3px rgba(0,0,0,0.08);color:var(--color-text-primary)">Day</div><div style="padding:5px 14px;border-radius:6px;font-size:12px;color:var(--color-text-tertiary)">Week</div><div style="padding:5px 14px;border-radius:6px;font-size:12px;color:var(--color-text-tertiary)">Month</div></div>'),
  'command-palette': () => W(`<div style="width:200px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:10px;box-shadow:var(--shadow-lg);overflow:hidden"><div style="display:flex;align-items:center;gap:6px;padding:8px 10px;border-bottom:1px solid var(--color-border-subtle)"><span style="color:var(--color-text-tertiary)">${I.search}</span><span style="font-size:12px;color:var(--color-text-tertiary)">Type a command...</span></div><div style="padding:4px"><div style="padding:5px 8px;font-size:11px;background:var(--color-surface-hover);border-radius:4px;color:var(--color-text-primary)">Open File</div><div style="padding:5px 8px;font-size:11px;color:var(--color-text-secondary)">Search</div></div></div>`),
  'mega-menu': () => W('<div style="width:200px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:8px;padding:10px;display:grid;grid-template-columns:1fr 1fr;gap:8px;box-shadow:var(--shadow-md)"><div><div style="font-size:9px;font-weight:600;color:var(--color-text-tertiary);text-transform:uppercase;margin-bottom:4px">Products</div><div style="font-size:11px;color:var(--color-text-secondary);line-height:1.8">Item A<br>Item B</div></div><div><div style="font-size:9px;font-weight:600;color:var(--color-text-tertiary);text-transform:uppercase;margin-bottom:4px">Resources</div><div style="font-size:11px;color:var(--color-text-secondary);line-height:1.8">Docs<br>Blog</div></div></div>'),
  'dropdown-menu': () => W(`<div class="demo-dropdown-mini open" style="position:relative"><div class="demo-dropdown-trigger">Menu ${I.chev}</div><div class="demo-dropdown-list" style="opacity:1;transform:none;pointer-events:auto;position:relative;top:4px"><div class="demo-dropdown-option">Edit</div><div class="demo-dropdown-option">Duplicate</div><div class="demo-dropdown-option" style="color:#ef4444">Delete</div></div></div>`),
  'context-menu': () => W('<div style="width:120px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:8px;box-shadow:var(--shadow-lg);padding:4px"><div style="padding:5px 10px;font-size:11px;border-radius:4px;color:var(--color-text-primary)">Cut</div><div style="padding:5px 10px;font-size:11px;border-radius:4px;color:var(--color-text-primary)">Copy</div><div style="padding:5px 10px;font-size:11px;border-radius:4px;color:var(--color-text-primary)">Paste</div><div style="height:1px;background:var(--color-border-subtle);margin:4px 0"></div><div style="padding:5px 10px;font-size:11px;border-radius:4px;color:#ef4444">Delete</div></div>'),
  'kebab-menu': () => W('<div style="display:flex;flex-direction:column;gap:2px;cursor:pointer;padding:6px"><div style="width:4px;height:4px;border-radius:50%;background:var(--color-text-tertiary)"></div><div style="width:4px;height:4px;border-radius:50%;background:var(--color-text-tertiary)"></div><div style="width:4px;height:4px;border-radius:50%;background:var(--color-text-tertiary)"></div></div>'),
  'meatball-menu': () => W('<div style="display:flex;gap:2px;cursor:pointer;padding:6px"><div style="width:4px;height:4px;border-radius:50%;background:var(--color-text-tertiary)"></div><div style="width:4px;height:4px;border-radius:50%;background:var(--color-text-tertiary)"></div><div style="width:4px;height:4px;border-radius:50%;background:var(--color-text-tertiary)"></div></div>'),
  'back-to-top-button': () => W(`<button class="demo-btn-icon" style="width:40px;height:40px;background:var(--color-surface);border:1px solid var(--color-border);box-shadow:var(--shadow-md)">${I.arrU}</button>`),

  // ── Display / Content ──
  'card': () => W('<div class="demo-card-mini"><div class="demo-card-mini-img"></div><div class="demo-card-mini-body"><div class="demo-card-mini-title">Card Title</div><div class="demo-card-mini-desc">Brief description</div></div></div>'),
  'avatar': () => WS('gap:6px', '<div class="demo-avatar" style="background:#3b82f6">A</div><div class="demo-avatar" style="background:#8b5cf6;width:32px;height:32px;font-size:13px">B</div><div class="demo-avatar" style="background:#ef4444;width:28px;height:28px;font-size:11px">C</div>'),
  'badge': () => WS('gap:12px', `<div style="position:relative;display:inline-flex"><button class="demo-btn-icon">${I.bell}</button><span class="demo-badge" style="position:absolute;top:-4px;right:-4px">3</span></div><span class="demo-badge">12</span><span class="demo-badge" style="background:#22c55e">New</span>`),
  'pill': () => WS('gap:6px', '<span style="padding:3px 12px;border-radius:99px;background:#eff6ff;color:#2563eb;font-size:11px;font-weight:500">Active</span><span style="padding:3px 12px;border-radius:99px;background:#fef2f2;color:#dc2626;font-size:11px;font-weight:500">Closed</span>'),
  'tag': () => WS('gap:6px', '<span class="demo-chip">Design</span><span class="demo-chip" style="background:#f0fdf4;color:#16a34a;border-color:#bbf7d0">New</span>'),
  'chip': () => WS('gap:6px', '<span class="demo-chip">React</span><span class="demo-chip" style="background:#fef3c7;color:#d97706;border-color:#fde68a">Vue</span>'),
  'tooltip': () => W('<div class="demo-tooltip-trigger">Hover me<div class="demo-tooltip-box">Tooltip text</div></div>'),
  'carousel': () => W('<div style="display:flex;flex-direction:column;align-items:center;gap:8px"><div style="width:160px;height:50px;background:linear-gradient(135deg,#667eea,#764ba2);border-radius:8px;display:flex;align-items:center;justify-content:center;color:white;font-size:11px">Slide 1</div><div style="display:flex;gap:5px"><div style="width:8px;height:8px;border-radius:50%;background:#3b82f6"></div><div style="width:8px;height:8px;border-radius:50%;background:#d1d5db"></div><div style="width:8px;height:8px;border-radius:50%;background:#d1d5db"></div></div></div>'),
  'progress-bar': () => WS('flex-direction:column;gap:6px', '<div class="demo-progress"><div class="demo-progress-bar" style="width:65%"></div></div><span style="font-size:10px;color:var(--color-text-tertiary)">65%</span>'),
  'spinner': () => W('<div class="demo-spinner"></div>'),
  'skeleton-screen': () => W('<div class="demo-skeleton"><div class="demo-skeleton-line"></div><div class="demo-skeleton-line"></div><div class="demo-skeleton-line"></div></div>'),
  'skeleton': () => W('<div class="demo-skeleton"><div class="demo-skeleton-line"></div><div class="demo-skeleton-line"></div><div class="demo-skeleton-line"></div></div>'),
  'shimmer': () => W('<div class="demo-skeleton" style="width:140px"><div class="demo-skeleton-line"></div><div class="demo-skeleton-line"></div></div>'),
  'toast': () => W(`<div class="demo-toast"><span style="color:#22c55e">${I.checkC}</span><span>Saved successfully</span></div>`),
  'snackbar': () => W('<div style="display:flex;align-items:center;gap:12px;padding:8px 14px;background:#1f2937;color:white;border-radius:8px;font-size:12px;box-shadow:0 4px 16px rgba(0,0,0,0.15)"><span>Item deleted</span><button style="color:#60a5fa;font-size:11px;font-weight:600;background:none;border:none;cursor:pointer">UNDO</button></div>'),
  'empty-state': () => W(`<div style="display:flex;flex-direction:column;align-items:center;gap:6px;padding:10px"><div style="width:36px;height:36px;background:var(--color-surface-hover);border-radius:50%;display:flex;align-items:center;justify-content:center;color:var(--color-text-tertiary)">${I.search}</div><span style="font-size:11px;color:var(--color-text-tertiary)">No results found</span></div>`),
  'status-indicator': () => WS('gap:12px', [{ c:'#22c55e', l:'Online' },{ c:'#f59e0b', l:'Away' },{ c:'#ef4444', l:'Busy' }].map(({c,l}) => `<div style="display:flex;align-items:center;gap:5px;font-size:11px;color:var(--color-text-secondary)"><div style="width:8px;height:8px;border-radius:50%;background:${c}"></div>${l}</div>`).join('')),
  'timeline': () => W('<div style="display:flex;flex-direction:column;padding-left:12px">'+['Event A','Event B','Event C'].map((t,i)=> `<div style="display:flex;align-items:flex-start;gap:8px;position:relative"><div style="position:absolute;left:-12px;top:2px;width:8px;height:8px;border-radius:50%;background:${i===0?'#3b82f6':'#d1d5db'};z-index:1"></div>${i<2?'<div style="position:absolute;left:-9px;top:10px;width:2px;height:16px;background:#e5e7eb"></div>':''}<span style="font-size:11px;color:var(--color-text-secondary);padding:0 0 10px 4px">${t}</span></div>`).join('')+'</div>'),
  'icon': () => WS('gap:8px', `<span style="color:#3b82f6">${I.layers}</span><span style="color:#8b5cf6">${I.gear}</span><span style="color:#ef4444">${I.bell}</span><span style="color:#f59e0b">${I.star}</span><span style="color:#22c55e">${I.checkC}</span>`),
  'counter': () => W('<div style="display:flex;align-items:center;gap:4px;font-size:18px;font-weight:700;font-family:var(--font-mono);color:var(--color-text-primary)">1,234</div>'),
  'hero': () => W('<div style="width:200px;height:60px;background:linear-gradient(135deg,#1e3a5f,#3b82f6);border-radius:8px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px"><span style="color:white;font-size:12px;font-weight:600">Welcome</span><span style="color:rgba(255,255,255,0.7);font-size:9px">Hero Section</span></div>'),
  'banner': () => W('<div style="width:200px;padding:8px 12px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;display:flex;align-items:center;gap:8px;font-size:11px;color:#1d4ed8">' + I.bell + 'New feature available!</div>'),
  'media-object': () => W('<div style="display:flex;gap:10px;align-items:flex-start"><div style="width:36px;height:36px;border-radius:8px;background:linear-gradient(135deg,#667eea,#764ba2);flex-shrink:0"></div><div><div style="font-size:12px;font-weight:500;color:var(--color-text-primary)">Title</div><div style="font-size:10px;color:var(--color-text-tertiary)">Description text here</div></div></div>'),
  'thumbnail': () => W('<div style="width:48px;height:48px;border-radius:6px;background:linear-gradient(135deg,#667eea,#764ba2);display:flex;align-items:center;justify-content:center;color:white;font-size:18px">' + I.eye + '</div>'),
  'list': () => WS('flex-direction:column;align-items:stretch;gap:0;width:160px', ['Item 1','Item 2','Item 3'].map(t=>`<div style="padding:6px 10px;border-bottom:1px solid var(--color-border-subtle);font-size:11px;color:var(--color-text-secondary)">${t}</div>`).join('')),
  'dot-indicator': () => WS('gap:6px', '<div style="width:8px;height:8px;border-radius:50%;background:#3b82f6"></div><div style="width:8px;height:8px;border-radius:50%;background:#d1d5db"></div><div style="width:8px;height:8px;border-radius:50%;background:#d1d5db"></div>'),

  // ── Overlays ──
  'modal': () => W(`<div class="demo-modal-mini"><div class="demo-modal-mini-header"><span class="demo-modal-mini-title">Confirm</span><span class="demo-modal-mini-close">${I.close}</span></div><div class="demo-modal-mini-body"><span class="demo-modal-mini-text">Are you sure?</span></div><div class="demo-modal-mini-footer"><button class="demo-btn demo-btn-ghost" style="padding:4px 10px;font-size:11px">Cancel</button><button class="demo-btn demo-btn-primary" style="padding:4px 10px;font-size:11px">OK</button></div></div>`),
  'popover': () => W('<div style="position:relative"><button class="demo-btn demo-btn-ghost" style="font-size:11px;padding:4px 12px">Click</button><div style="position:absolute;bottom:calc(100% + 6px);left:50%;transform:translateX(-50%);background:var(--color-surface);border:1px solid var(--color-border);border-radius:8px;padding:8px 12px;box-shadow:0 4px 12px rgba(0,0,0,0.1);white-space:nowrap"><div style="font-size:11px;color:var(--color-text-secondary)">Popover content</div><div style="position:absolute;top:100%;left:50%;transform:translateX(-50%);border:5px solid transparent;border-top-color:var(--color-border)"></div></div></div>'),
  'bottom-sheet': () => W('<div style="width:140px;height:80px;background:rgba(0,0,0,0.15);border-radius:8px;position:relative;overflow:hidden"><div style="position:absolute;bottom:0;left:0;right:0;height:55%;background:var(--color-surface);border-radius:12px 12px 0 0;box-shadow:0 -2px 10px rgba(0,0,0,0.08);display:flex;flex-direction:column;align-items:center;padding-top:6px"><div style="width:28px;height:3px;background:#d1d5db;border-radius:2px;margin-bottom:6px"></div><span style="font-size:10px;color:var(--color-text-tertiary)">Sheet content</span></div></div>'),
  'alert': () => W(`<div style="display:flex;align-items:flex-start;gap:8px;padding:8px 12px;background:#fef2f2;border:1px solid #fecaca;border-radius:8px;width:180px"><span style="color:#ef4444;flex-shrink:0">${I.close}</span><span style="font-size:11px;color:#991b1b">Something went wrong.</span></div>`),
  'notification': () => W(`<div style="display:flex;align-items:flex-start;gap:8px;padding:8px 12px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:8px;width:180px;box-shadow:var(--shadow-md)"><span style="color:#3b82f6">${I.bell}</span><div><div style="font-size:11px;font-weight:500">New message</div><div style="font-size:10px;color:var(--color-text-tertiary)">2 min ago</div></div></div>`),
  'overlay': () => W('<div style="width:140px;height:60px;border:1px solid var(--color-border);border-radius:6px;position:relative;overflow:hidden"><div style="position:absolute;inset:0;background:rgba(0,0,0,0.4);display:flex;align-items:center;justify-content:center;color:white;font-size:10px">Overlay</div><div style="padding:8px;font-size:10px;color:var(--color-text-tertiary)">Content</div></div>'),
  'scrim': () => W('<div style="width:140px;height:60px;border:1px solid var(--color-border);border-radius:6px;position:relative;overflow:hidden"><div style="position:absolute;inset:0;background:rgba(0,0,0,0.5);backdrop-filter:blur(2px)"></div><div style="padding:8px;font-size:10px;color:var(--color-text-tertiary)">Behind scrim</div></div>'),

  // ── Table / Data ──
  'table': () => W('<table class="demo-table"><thead><tr><th>Name</th><th>Role</th></tr></thead><tbody><tr><td>Alice</td><td>Designer</td></tr><tr><td>Bob</td><td>Developer</td></tr></tbody></table>'),
  'data-table': () => W(`<table class="demo-table"><thead><tr><th style="width:14px"><div style="width:12px;height:12px;border:1.5px solid #d1d5db;border-radius:3px"></div></th><th>Name</th><th>Status</th></tr></thead><tbody><tr><td><div style="width:12px;height:12px;border:1.5px solid #3b82f6;border-radius:3px;background:#3b82f6;display:flex;align-items:center;justify-content:center;color:white">${I.check}</div></td><td>Alice</td><td><span style="color:#22c55e;font-size:10px">Active</span></td></tr><tr><td><div style="width:12px;height:12px;border:1.5px solid #d1d5db;border-radius:3px"></div></td><td>Bob</td><td><span style="color:#f59e0b;font-size:10px">Pending</span></td></tr></tbody></table>`),
  'accordion': () => W(`<div class="demo-accordion"><div class="demo-accordion-item open" data-demo-toggle="accordion"><div class="demo-accordion-header">Section 1 <span class="demo-accordion-chevron">${I.chev}</span></div><div class="demo-accordion-body"><div class="demo-accordion-content">Content for section one.</div></div></div><div class="demo-accordion-item" data-demo-toggle="accordion"><div class="demo-accordion-header">Section 2 <span class="demo-accordion-chevron">${I.chev}</span></div><div class="demo-accordion-body"><div class="demo-accordion-content">Content for section two.</div></div></div></div>`),
  'disclosure': () => W(`<div class="demo-accordion" style="width:180px"><div class="demo-accordion-item open" data-demo-toggle="accordion"><div class="demo-accordion-header">Details <span class="demo-accordion-chevron">${I.chev}</span></div><div class="demo-accordion-body"><div class="demo-accordion-content">Hidden content revealed.</div></div></div></div>`),
  'zebra-striping': () => W('<div style="width:180px;border:1px solid var(--color-border);border-radius:6px;overflow:hidden;font-size:11px"><div style="padding:4px 8px;background:var(--color-surface-hover)">Row 1</div><div style="padding:4px 8px">Row 2</div><div style="padding:4px 8px;background:var(--color-surface-hover)">Row 3</div><div style="padding:4px 8px">Row 4</div></div>'),

  // ── States ──
  'hover': () => W('<button class="demo-btn demo-btn-primary" style="transform:translateY(-1px);box-shadow:0 4px 12px rgba(59,130,246,0.35)">Hovered</button>'),
  'default-state': () => W('<button class="demo-btn demo-btn-primary">Default</button>'),
  'focus': () => W('<input class="demo-input" style="border-color:#3b82f6;box-shadow:0 0 0 3px rgba(59,130,246,0.12);width:150px" value="Focused" readonly>'),
  'focus-ring': () => W('<button class="demo-btn demo-btn-primary" style="outline:2px solid #3b82f6;outline-offset:2px">Focus Ring</button>'),
  'disabled-state': () => W('<button class="demo-btn demo-btn-primary" style="opacity:0.5;cursor:not-allowed">Disabled</button><input class="demo-input" style="opacity:0.5;width:80px;cursor:not-allowed" value="Off" disabled readonly>'),
  'active-state': () => W('<button class="demo-btn demo-btn-primary" style="transform:scale(0.96);box-shadow:none;background:#1d4ed8">Active</button>'),
  'pressed-state': () => W('<button class="demo-btn demo-btn-primary" style="transform:scale(0.96);background:#1d4ed8">Pressed</button>'),
  'loading-state': () => W('<button class="demo-btn demo-btn-primary" style="display:flex;align-items:center;gap:6px"><span class="demo-spinner" style="width:14px;height:14px;border-width:2px;border-color:rgba(255,255,255,0.3);border-top-color:white"></span>Loading...</button>'),
  'error-state': () => WS('flex-direction:column;gap:4px', '<input class="demo-input" style="border-color:#ef4444;box-shadow:0 0 0 3px rgba(239,68,68,0.1);width:160px" value="bad@" readonly><span style="font-size:10px;color:#ef4444">Invalid email</span>'),
  'success-state': () => W(`<div style="display:flex;align-items:center;gap:6px;padding:6px 12px;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;font-size:11px;color:#166534">${I.checkC} Success</div>`),
  'warning-state': () => W('<div style="display:flex;align-items:center;gap:6px;padding:6px 12px;background:#fffbeb;border:1px solid #fde68a;border-radius:8px;font-size:11px;color:#92400e">Warning</div>'),
  'selected-state': () => W('<div style="display:flex;gap:4px"><div style="padding:5px 14px;border-radius:6px;background:#3b82f6;color:white;font-size:12px">Selected</div><div style="padding:5px 14px;border-radius:6px;background:var(--color-surface-hover);font-size:12px;color:var(--color-text-tertiary)">Normal</div></div>'),
  'checked-state': () => W(`<label class="demo-checkbox checked"><span class="demo-checkbox-box"><span class="demo-checkbox-check">${I.check}</span></span><span>Checked</span></label>`),
  'expanded-state': () => W(`<div style="display:flex;align-items:center;gap:6px;font-size:12px;color:var(--color-text-primary)"><span style="transform:rotate(180deg);display:inline-flex">${I.chev}</span> Expanded</div>`),
  'collapsed-state': () => W(`<div style="display:flex;align-items:center;gap:6px;font-size:12px;color:var(--color-text-tertiary)"><span style="transform:rotate(-90deg);display:inline-flex">${I.chev}</span> Collapsed</div>`),

  // ── Layout ──
  'grid-system': () => W('<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:4px;width:160px">' + Array(4).fill('<div style="height:30px;background:rgba(59,130,246,0.15);border-radius:4px;border:1px dashed rgba(59,130,246,0.3)"></div>').join('') + '</div>'),
  'flex-layout': () => W('<div style="display:flex;gap:4px;width:160px"><div style="flex:1;height:30px;background:rgba(139,92,246,0.15);border-radius:4px;border:1px dashed rgba(139,92,246,0.3)"></div><div style="flex:2;height:30px;background:rgba(139,92,246,0.2);border-radius:4px;border:1px dashed rgba(139,92,246,0.3)"></div><div style="flex:1;height:30px;background:rgba(139,92,246,0.15);border-radius:4px;border:1px dashed rgba(139,92,246,0.3)"></div></div>'),
  'masonry-layout': () => W('<div style="display:flex;gap:4px;width:140px"><div style="display:flex;flex-direction:column;gap:4px;flex:1"><div style="height:32px;background:rgba(59,130,246,0.12);border-radius:4px"></div><div style="height:20px;background:rgba(59,130,246,0.12);border-radius:4px"></div></div><div style="display:flex;flex-direction:column;gap:4px;flex:1"><div style="height:20px;background:rgba(59,130,246,0.12);border-radius:4px"></div><div style="height:32px;background:rgba(59,130,246,0.12);border-radius:4px"></div></div></div>'),
  'responsive-breakpoint': () => WS('gap:8px', [{w:20,l:'SM'},{w:32,l:'MD'},{w:48,l:'LG'}].map(({w,l})=>`<div style="width:${w}px;height:28px;background:rgba(59,130,246,0.12);border:1px solid rgba(59,130,246,0.25);border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:9px;color:#3b82f6;font-weight:600">${l}</div>`).join('')),
  'split-layout': () => W('<div style="display:flex;width:160px;height:60px;border:1px solid var(--color-border);border-radius:6px;overflow:hidden"><div style="flex:1;border-right:2px solid var(--color-border);display:flex;align-items:center;justify-content:center;font-size:9px;color:var(--color-text-tertiary)">Left</div><div style="flex:1;display:flex;align-items:center;justify-content:center;font-size:9px;color:var(--color-text-tertiary)">Right</div></div>'),
  'dashboard-layout': () => W('<div style="display:grid;grid-template-columns:1fr 1fr;gap:4px;width:160px"><div style="height:30px;background:rgba(59,130,246,0.1);border-radius:4px;grid-column:span 2;border:1px solid rgba(59,130,246,0.2)"></div><div style="height:24px;background:rgba(139,92,246,0.1);border-radius:4px;border:1px solid rgba(139,92,246,0.2)"></div><div style="height:24px;background:rgba(236,72,153,0.1);border-radius:4px;border:1px solid rgba(236,72,153,0.2)"></div></div>'),
  'container': () => W('<div style="width:180px;border:2px dashed rgba(59,130,246,0.3);border-radius:8px;padding:8px;display:flex;align-items:center;justify-content:center;font-size:10px;color:#3b82f6">Container</div>'),
  'header': () => W('<div style="width:180px"><div style="height:20px;background:var(--color-surface-hover);border-bottom:1px solid var(--color-border);border-radius:6px 6px 0 0;display:flex;align-items:center;padding:0 8px;font-size:9px;color:var(--color-text-tertiary)">Header</div><div style="height:40px;border:1px solid var(--color-border-subtle);border-top:0;border-radius:0 0 6px 6px"></div></div>'),
  'footer': () => W('<div style="width:180px"><div style="height:40px;border:1px solid var(--color-border-subtle);border-bottom:0;border-radius:6px 6px 0 0"></div><div style="height:20px;background:var(--color-surface-hover);border-top:1px solid var(--color-border);border-radius:0 0 6px 6px;display:flex;align-items:center;padding:0 8px;font-size:9px;color:var(--color-text-tertiary)">Footer</div></div>'),
  'margin': () => W('<div style="padding:10px;background:rgba(59,130,246,0.08);border-radius:8px;border:1px dashed rgba(59,130,246,0.3)"><div style="font-size:8px;color:#3b82f6;margin-bottom:4px">margin</div><div style="width:80px;height:30px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:4px"></div></div>'),
  'padding': () => W('<div style="border:1px solid var(--color-border);border-radius:8px"><div style="padding:10px;background:rgba(139,92,246,0.08)"><div style="font-size:8px;color:#8b5cf6;margin-bottom:4px">padding</div><div style="width:80px;height:20px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:4px"></div></div></div>'),

  // ── Typography ──
  'font-size': () => WS('flex-direction:column;align-items:flex-start;gap:2px', '<span style="font-size:16px;font-weight:500">Large 16px</span><span style="font-size:13px;color:var(--color-text-secondary)">Default 13px</span><span style="font-size:10px;color:var(--color-text-tertiary)">Small 10px</span>'),
  'font-weight': () => WS('flex-direction:column;align-items:flex-start;gap:2px', '<span style="font-weight:300;font-size:13px">Light 300</span><span style="font-weight:400;font-size:13px">Regular 400</span><span style="font-weight:600;font-size:13px">Semi 600</span><span style="font-weight:700;font-size:13px">Bold 700</span>'),
  'line-height': () => WS('gap:12px', '<div style="font-size:10px;color:var(--color-text-secondary);line-height:1;width:60px;border-left:2px solid #3b82f6;padding-left:6px">Line height 1.0 tight</div><div style="font-size:10px;color:var(--color-text-secondary);line-height:1.8;width:60px;border-left:2px solid #8b5cf6;padding-left:6px">Line height 1.8 loose</div>'),
  'letter-spacing': () => WS('flex-direction:column;align-items:flex-start;gap:4px', '<span style="font-size:12px;letter-spacing:0">Normal spacing</span><span style="font-size:12px;letter-spacing:2px">Wide spacing</span><span style="font-size:12px;letter-spacing:4px;color:var(--color-text-secondary)">Extra wide</span>'),
  'heading': () => WS('flex-direction:column;align-items:flex-start;gap:2px', '<span style="font-size:18px;font-weight:700">Heading 1</span><span style="font-size:14px;font-weight:600;color:var(--color-text-secondary)">Heading 2</span><span style="font-size:12px;font-weight:500;color:var(--color-text-tertiary)">Heading 3</span>'),
  'body-text': () => W('<p style="font-size:13px;line-height:1.6;color:var(--color-text-secondary);max-width:180px">The quick brown fox jumps over the lazy dog.</p>'),
  'monospace': () => W('<code style="font-family:var(--font-mono);font-size:12px;padding:4px 8px;background:var(--color-surface-hover);border-radius:4px;color:var(--color-accent-text)">const x = 42</code>'),
  'truncation': () => W('<div style="width:140px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:12px;color:var(--color-text-secondary)">This is a very long text that gets truncated</div>'),
  'ellipsis': () => W('<div style="width:140px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:12px;color:var(--color-text-secondary)">This text is too long to fit...</div>'),
  'text-alignment': () => WS('flex-direction:column;gap:2px;width:120px', '<div style="text-align:left;font-size:10px;color:var(--color-text-secondary);padding:2px 6px;background:var(--color-surface-hover);border-radius:3px">Left</div><div style="text-align:center;font-size:10px;color:var(--color-text-secondary);padding:2px 6px;background:var(--color-surface-hover);border-radius:3px">Center</div><div style="text-align:right;font-size:10px;color:var(--color-text-secondary);padding:2px 6px;background:var(--color-surface-hover);border-radius:3px">Right</div>'),
  'microcopy': () => W('<div style="display:flex;flex-direction:column;gap:4px;font-size:11px"><span style="color:var(--color-text-secondary)">No account? <span style="color:#3b82f6;font-weight:500">Sign up</span></span><span style="color:#ef4444">Password is required</span></div>'),
  'information-hierarchy': () => WS('flex-direction:column;align-items:flex-start;gap:1px', '<span style="font-size:16px;font-weight:700">Title</span><span style="font-size:12px;color:var(--color-text-secondary)">Subtitle</span><span style="font-size:10px;color:var(--color-text-tertiary)">Caption text</span>'),

  // ── Color / Visual ──
  'color-palette': () => W('<div class="demo-color-row">' + ['#3b82f6','#8b5cf6','#ef4444','#22c55e','#f59e0b','#ec4899'].map(c => `<div class="demo-color-swatch" style="background:${c}"></div>`).join('') + '</div>'),
  'gradient': () => W('<div style="width:160px;height:32px;border-radius:8px;background:linear-gradient(135deg,#667eea 0%,#764ba2 50%,#f093fb 100%)"></div>'),
  'shadow': () => WS('gap:12px', '<div style="width:40px;height:40px;background:var(--color-surface);border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,0.1)"></div><div style="width:40px;height:40px;background:var(--color-surface);border-radius:8px;box-shadow:0 4px 12px rgba(0,0,0,0.15)"></div><div style="width:40px;height:40px;background:var(--color-surface);border-radius:8px;box-shadow:0 8px 24px rgba(0,0,0,0.2)"></div>'),
  'dark-mode': () => WS('gap:6px', '<div style="width:60px;height:40px;background:#fff;border:1px solid #e5e7eb;border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:9px;color:#1f2937">Light</div><div style="width:60px;height:40px;background:#1a1d26;border:1px solid #3d4150;border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:9px;color:#e8eaed">Dark</div>'),
  'opacity': () => WS('gap:4px', [1,0.7,0.4,0.15].map(o => `<div style="width:28px;height:28px;background:#3b82f6;opacity:${o};border-radius:6px"></div>`).join('')),
  'border': () => WS('gap:8px', '<div style="width:36px;height:36px;border:2px solid #3b82f6;border-radius:6px"></div><div style="width:36px;height:36px;border:2px dashed #8b5cf6;border-radius:6px"></div><div style="width:36px;height:36px;border:2px dotted #ef4444;border-radius:6px"></div>'),
  'border-radius': () => WS('gap:6px', '<div style="width:32px;height:32px;background:#3b82f6;border-radius:0"></div><div style="width:32px;height:32px;background:#3b82f6;border-radius:6px"></div><div style="width:32px;height:32px;background:#3b82f6;border-radius:50%"></div>'),
  'radius': () => WS('gap:6px', '<div style="width:32px;height:32px;background:#3b82f6;border-radius:0"></div><div style="width:32px;height:32px;background:#3b82f6;border-radius:6px"></div><div style="width:32px;height:32px;background:#3b82f6;border-radius:50%"></div>'),
  'blur': () => WS('gap:8px', '<div style="width:40px;height:40px;background:#3b82f6;border-radius:8px"></div><div style="width:40px;height:40px;background:#3b82f6;border-radius:8px;filter:blur(2px)"></div><div style="width:40px;height:40px;background:#3b82f6;border-radius:8px;filter:blur(5px)"></div>'),
  'divider': () => WS('flex-direction:column;gap:8px;width:160px', '<span style="font-size:10px;color:var(--color-text-tertiary)">Section A</span><div style="height:1px;background:var(--color-border)"></div><span style="font-size:10px;color:var(--color-text-tertiary)">Section B</span>'),
  'elevation': () => WS('gap:8px', [1,2,3].map(i => `<div style="width:40px;height:40px;background:var(--color-surface);border-radius:8px;box-shadow:0 ${i*2}px ${i*6}px rgba(0,0,0,${0.04+i*0.04})"></div>`).join('')),
  'design-token': () => W('<div style="font-family:var(--font-mono);font-size:10px;display:flex;flex-direction:column;gap:3px"><div style="display:flex;align-items:center;gap:6px"><div style="width:14px;height:14px;border-radius:3px;background:#3b82f6"></div>--blue-500</div><div style="display:flex;align-items:center;gap:6px"><div style="width:14px;height:14px;border-radius:3px;background:#8b5cf6"></div>--purple-500</div><div style="display:flex;align-items:center;gap:6px"><div style="width:14px;height:14px;border-radius:50%;background:var(--color-surface-hover);display:flex;align-items:center;justify-content:center;font-size:8px">16</div>--space-4</div></div>'),
  'theme': () => WS('gap:4px', '<div style="width:30px;height:30px;border-radius:6px;background:#3b82f6"></div><div style="width:30px;height:30px;border-radius:6px;background:#1e40af"></div><div style="width:30px;height:30px;border-radius:6px;background:#93c5fd"></div><div style="width:30px;height:30px;border-radius:6px;background:#dbeafe"></div>'),
  'semantic-color': () => WS('gap:4px', [['#22c55e','OK'],['#f59e0b','!'],['#ef4444','X'],['#3b82f6','i']].map(([c,l])=>`<div style="width:28px;height:28px;border-radius:6px;background:${c};display:flex;align-items:center;justify-content:center;color:white;font-size:10px;font-weight:600">${l}</div>`).join('')),

  // ── Animation ──
  'transition': () => W('<div style="width:36px;height:36px;background:#3b82f6;border-radius:8px;transition:all 0.3s ease;cursor:pointer" onmouseenter="this.style.borderRadius=\'50%\';this.style.background=\'#8b5cf6\'" onmouseleave="this.style.borderRadius=\'8px\';this.style.background=\'#3b82f6\'"></div><span style="font-size:10px;color:var(--color-text-tertiary)">Hover me</span>'),
  'fade': () => WS('gap:6px', '<div style="width:32px;height:32px;background:#3b82f6;border-radius:6px;opacity:1"></div><div style="width:32px;height:32px;background:#3b82f6;border-radius:6px;opacity:0.5"></div><div style="width:32px;height:32px;background:#3b82f6;border-radius:6px;opacity:0.15"></div>'),
  'easing': () => W(`${svg(160,40,'<path d="M5 35 C30 35 10 5 80 5 C150 5 130 35 155 35" stroke="#3b82f6" stroke-width="2" fill="none"/><circle cx="80" cy="5" r="3" fill="#3b82f6"/>')}`),
  'spring-animation': () => W('<div style="width:28px;height:28px;background:#3b82f6;border-radius:6px;animation:bounce 1s ease infinite"></div>'),
  'animation': () => W('<div style="width:28px;height:28px;background:#8b5cf6;border-radius:6px;animation:wiggle 1s ease infinite"></div>'),
  'parallax': () => W('<div style="width:140px;height:50px;border-radius:6px;position:relative;overflow:hidden"><div style="position:absolute;inset:0;background:linear-gradient(135deg,#1e3a5f,#3b82f6)"></div><div style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:white;font-size:11px">Parallax</div></div>'),
  'loading-animation': () => WS('gap:4px', [0,1,2].map(i => `<div style="width:8px;height:8px;border-radius:50%;background:#3b82f6;animation:typing 1s ${i*0.2}s ease infinite"></div>`).join('')),
  'microanimation': () => W('<div style="width:28px;height:28px;display:flex;align-items:center;justify-content:center;cursor:pointer;animation:float 2s ease-in-out infinite"><span style="color:#ef4444;font-size:20px">&hearts;</span></div>'),

  // ── Charts ──
  'bar-chart': () => W(svg(140,60,[{x:10,h:35},{x:35,h:50},{x:60,h:25},{x:85,h:45},{x:110,h:30}].map(({x,h})=>`<rect x="${x}" y="${60-h}" width="18" height="${h}" rx="3" fill="#3b82f6" opacity="0.8"/>`).join(''))),
  'line-chart': () => W(svg(140,60,'<polyline points="5,45 30,25 55,35 80,15 105,30 130,10" fill="none" stroke="#3b82f6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>'+[[5,45],[30,25],[55,35],[80,15],[105,30],[130,10]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="2.5" fill="#3b82f6"/>`).join(''))),
  'pie-chart': () => W(svg(60,60,'<circle cx="30" cy="30" r="28" fill="#3b82f6"/><path d="M30 30 L30 2 A28 28 0 0 1 55 38 Z" fill="#8b5cf6"/><path d="M30 30 L55 38 A28 28 0 0 1 30 58 Z" fill="#f59e0b"/>')),
  'donut-chart': () => W(svg(60,60,'<circle cx="30" cy="30" r="22" fill="none" stroke="#e5e7eb" stroke-width="8"/><circle cx="30" cy="30" r="22" fill="none" stroke="#3b82f6" stroke-width="8" stroke-dasharray="103.67 138.23" stroke-linecap="round" transform="rotate(-90 30 30)"/><text x="30" y="33" text-anchor="middle" font-size="12" font-weight="600" fill="var(--color-text-primary)">75%</text>')),
  'gauge': () => W(svg(80,50,'<path d="M10 45 A30 30 0 0 1 70 45" fill="none" stroke="#e5e7eb" stroke-width="6" stroke-linecap="round"/><path d="M10 45 A30 30 0 0 1 55 18" fill="none" stroke="#3b82f6" stroke-width="6" stroke-linecap="round"/><text x="40" y="42" text-anchor="middle" font-size="12" font-weight="600" fill="var(--color-text-primary)">72</text>')),
  'sparkline': () => W(svg(80,24,'<polyline points="2,18 12,14 22,20 32,10 42,16 52,6 62,12 72,4 78,8" fill="none" stroke="#3b82f6" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>')),
  'heatmap': () => W('<div style="display:grid;grid-template-columns:repeat(5,1fr);gap:2px">'+[0.9,0.3,0.6,0.1,0.8,0.4,0.7,0.2,0.5,1].map(v=>`<div style="width:18px;height:18px;border-radius:3px;background:rgba(59,130,246,${v})"></div>`).join('')+'</div>'),
  'radar-chart': () => W(svg(70,70,'<polygon points="35,10 55,25 50,50 20,50 15,25" fill="rgba(59,130,246,0.15)" stroke="#3b82f6" stroke-width="1.5"/><polygon points="35,20 47,30 44,45 26,45 23,30" fill="none" stroke="#e5e7eb" stroke-width="0.5"/>')),
  'scatter-plot': () => W(svg(100,60,[[15,40],[25,25],[35,45],[50,20],[60,35],[75,15],[85,30],[90,10]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="3" fill="#3b82f6" opacity="0.7"/>`).join(''))),
  'area-chart': () => W(svg(140,50,'<path d="M5,40 L30,25 L55,30 L80,15 L105,22 L130,8 L130,45 L5,45 Z" fill="rgba(59,130,246,0.15)" stroke="none"/><polyline points="5,40 30,25 55,30 80,15 105,22 130,8" fill="none" stroke="#3b82f6" stroke-width="1.5"/>')),
  'histogram': () => W(svg(120,50,[{x:5,h:20},{x:20,h:35},{x:35,h:45},{x:50,h:40},{x:65,h:30},{x:80,h:15},{x:95,h:8}].map(({x,h})=>`<rect x="${x}" y="${50-h}" width="13" height="${h}" fill="#3b82f6" opacity="0.7"/>`).join(''))),
  'candlestick-chart': () => W(svg(120,50,[{x:15,o:35,c:20,h:15,l:40},{x:35,o:18,c:30,h:12,l:35},{x:55,o:28,c:15,h:10,l:33},{x:75,o:20,c:32,h:10,l:38},{x:95,o:30,c:22,h:18,l:35}].map(({x,o,c,h,l})=>{const up=c<o;return `<line x1="${x}" y1="${h}" x2="${x}" y2="${l}" stroke="${up?'#22c55e':'#ef4444'}" stroke-width="1"/><rect x="${x-4}" y="${Math.min(o,c)}" width="8" height="${Math.abs(o-c)||1}" fill="${up?'#22c55e':'#ef4444'}"/>`}).join(''))),

  // ── EC / SaaS ──
  'product-card': () => W('<div style="width:120px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:8px;overflow:hidden"><div style="height:40px;background:linear-gradient(135deg,#ec4899,#8b5cf6)"></div><div style="padding:6px 8px"><div style="font-size:11px;font-weight:500">Product</div><div style="font-size:12px;font-weight:600;color:#3b82f6;margin-top:2px">$29.99</div></div></div>'),
  'cart': () => W(`<div style="display:flex;align-items:center;gap:6px;padding:6px 12px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:8px">${svg(18,18,'<circle cx="7" cy="15" r="1.5"/><circle cx="14" cy="15" r="1.5"/><path d="M1 1h3l2 10h9l2-6H6"/>')}<span style="font-size:12px;font-weight:500">3 items</span><span class="demo-badge" style="font-size:10px">$89</span></div>`),
  'dashboard': () => W('<div style="display:grid;grid-template-columns:1fr 1fr;gap:4px;width:160px"><div style="padding:6px 8px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:6px"><div style="font-size:8px;color:var(--color-text-tertiary)">Users</div><div style="font-size:14px;font-weight:700">1.2k</div></div><div style="padding:6px 8px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:6px"><div style="font-size:8px;color:var(--color-text-tertiary)">Revenue</div><div style="font-size:14px;font-weight:700;color:#22c55e">$4.5k</div></div></div>'),
  'kpi-card': () => W('<div style="padding:8px 12px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:8px;width:120px"><div style="font-size:9px;color:var(--color-text-tertiary)">Monthly Active</div><div style="font-size:18px;font-weight:700;margin-top:2px">8,492</div><div style="font-size:10px;color:#22c55e;margin-top:2px">+12.3%</div></div>'),
  'review-stars': () => { const f=Array(4).fill(`<span style="color:#f59e0b">${I.star}</span>`).join(''); return W(f+`<span style="color:#d1d5db">${I.starE}</span><span style="font-size:11px;color:var(--color-text-tertiary);margin-left:4px">4.0</span>`) },
  'quantity-stepper': () => WS('gap:0', '<button style="width:28px;height:28px;border:1.5px solid #d1d5db;border-radius:6px 0 0 6px;background:var(--color-surface);display:flex;align-items:center;justify-content:center;cursor:pointer;font-size:14px;color:var(--color-text-secondary)">-</button><div style="width:36px;height:28px;border-top:1.5px solid #d1d5db;border-bottom:1.5px solid #d1d5db;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:500">2</div><button style="width:28px;height:28px;border:1.5px solid #d1d5db;border-radius:0 6px 6px 0;background:var(--color-surface);display:flex;align-items:center;justify-content:center;cursor:pointer;font-size:14px;color:var(--color-text-secondary)">+</button>'),
  'wishlist-button': () => W('<button style="width:36px;height:36px;border-radius:50%;border:1.5px solid #d1d5db;background:var(--color-surface);display:flex;align-items:center;justify-content:center;cursor:pointer;color:#ef4444;font-size:18px">&hearts;</button>'),
  'status-pill': () => WS('gap:6px', '<span style="padding:3px 10px;border-radius:99px;background:#f0fdf4;color:#16a34a;font-size:10px;font-weight:500">Active</span><span style="padding:3px 10px;border-radius:99px;background:#fef3c7;color:#d97706;font-size:10px;font-weight:500">Pending</span><span style="padding:3px 10px;border-radius:99px;background:#fef2f2;color:#dc2626;font-size:10px;font-weight:500">Error</span>'),
  'comment-thread': () => WS('flex-direction:column;gap:6px;align-items:flex-start', '<div style="display:flex;gap:6px"><div class="demo-avatar" style="background:#3b82f6;width:22px;height:22px;font-size:9px">A</div><div style="padding:4px 8px;background:var(--color-surface-hover);border-radius:6px;font-size:10px;max-width:140px">Great idea!</div></div><div style="display:flex;gap:6px;padding-left:28px"><div class="demo-avatar" style="background:#8b5cf6;width:22px;height:22px;font-size:9px">B</div><div style="padding:4px 8px;background:var(--color-surface-hover);border-radius:6px;font-size:10px">Thanks!</div></div>'),
  'presence-indicator': () => WS('gap:8px', '<div style="position:relative"><div class="demo-avatar" style="background:#3b82f6;width:30px;height:30px;font-size:12px">A</div><div style="position:absolute;bottom:-1px;right:-1px;width:10px;height:10px;border-radius:50%;background:#22c55e;border:2px solid var(--color-surface)"></div></div><div style="position:relative"><div class="demo-avatar" style="background:#8b5cf6;width:30px;height:30px;font-size:12px">B</div><div style="position:absolute;bottom:-1px;right:-1px;width:10px;height:10px;border-radius:50%;background:#d1d5db;border:2px solid var(--color-surface)"></div></div>'),
  'diff-view': () => W('<div style="font-family:var(--font-mono);font-size:9px;width:180px;border:1px solid var(--color-border);border-radius:6px;overflow:hidden"><div style="padding:2px 6px;background:#fef2f2;color:#991b1b">- old value</div><div style="padding:2px 6px;background:#f0fdf4;color:#166534">+ new value</div><div style="padding:2px 6px;color:var(--color-text-tertiary)">  unchanged</div></div>'),
  'mention': () => W('<span style="font-size:12px;color:var(--color-text-secondary)">Hey <span style="color:#3b82f6;font-weight:500;background:rgba(59,130,246,0.08);padding:1px 4px;border-radius:3px">@alice</span>, check this</span>'),
  'reaction': () => WS('gap:4px', ['👍 3','❤️ 2','🎉 1'].map(r => `<span style="padding:2px 8px;background:var(--color-surface-hover);border:1px solid var(--color-border);border-radius:99px;font-size:11px">${r}</span>`).join('')),
  'version-history': () => WS('flex-direction:column;gap:4px;align-items:flex-start', ['v2.1 — now','v2.0 — 2h ago','v1.9 — yesterday'].map((v,i) => `<div style="display:flex;align-items:center;gap:6px;font-size:10px;color:${i===0?'#3b82f6':'var(--color-text-tertiary)'};${i===0?'font-weight:500':''}"><div style="width:6px;height:6px;border-radius:50%;background:${i===0?'#3b82f6':'#d1d5db'}"></div>${v}</div>`).join('')),
  'permission-matrix': () => W('<table class="demo-table" style="width:170px"><thead><tr><th></th><th style="font-size:9px">R</th><th style="font-size:9px">W</th><th style="font-size:9px">D</th></tr></thead><tbody><tr><td style="font-size:10px">Admin</td><td style="color:#22c55e">' + I.check + '</td><td style="color:#22c55e">' + I.check + '</td><td style="color:#22c55e">' + I.check + '</td></tr><tr><td style="font-size:10px">User</td><td style="color:#22c55e">' + I.check + '</td><td style="color:#22c55e">' + I.check + '</td><td style="color:#d1d5db">-</td></tr></tbody></table>'),

  // ── File / Editor ──
  'file-tree': () => WS('flex-direction:column;align-items:flex-start;gap:2px;font-size:11px;font-family:var(--font-mono)', '<div style="color:var(--color-text-tertiary)">src/</div><div style="padding-left:12px;color:var(--color-text-secondary)">components/</div><div style="padding-left:24px;color:#3b82f6">Button.tsx</div><div style="padding-left:24px;color:var(--color-text-secondary)">Card.tsx</div><div style="padding-left:12px;color:var(--color-text-secondary)">utils.ts</div>'),
  'code-editor': () => W('<div style="width:180px;background:#1e1e2e;border-radius:6px;padding:8px 10px;font-family:var(--font-mono);font-size:10px;line-height:1.6"><span style="color:#c678dd">const</span> <span style="color:#e06c75">x</span> <span style="color:#56b6c2">=</span> <span style="color:#d19a66">42</span><br><span style="color:#c678dd">return</span> <span style="color:#e06c75">x</span> <span style="color:#56b6c2">*</span> <span style="color:#d19a66">2</span></div>'),
  'color-swatch': () => WS('gap:4px', ['#ef4444','#f59e0b','#22c55e','#3b82f6','#8b5cf6'].map(c=>`<div style="width:24px;height:24px;border-radius:50%;background:${c};border:2px solid rgba(255,255,255,0.5);box-shadow:0 1px 3px rgba(0,0,0,0.1)"></div>`).join('')),
  'minimap': () => W('<div style="width:30px;height:60px;background:#1e1e2e;border-radius:4px;position:relative;overflow:hidden"><div style="position:absolute;top:8px;right:0;width:20px;height:16px;background:rgba(59,130,246,0.2);border:1px solid rgba(59,130,246,0.4)"></div>'+[4,8,14,18,22,28,32,38,42,46].map(y=>`<div style="position:absolute;top:${y}px;left:3px;width:${8+hash(String(y))%14}px;height:1px;background:rgba(255,255,255,0.15)"></div>`).join('')+'</div>'),
  'resize-handle': () => W('<div style="width:80px;height:40px;border:2px solid #3b82f6;border-radius:6px;position:relative"><div style="position:absolute;bottom:-4px;right:-4px;width:8px;height:8px;background:#3b82f6;border-radius:2px;cursor:se-resize"></div><div style="position:absolute;right:-4px;top:50%;transform:translateY(-50%);width:8px;height:8px;background:#3b82f6;border-radius:2px;cursor:e-resize"></div></div>'),
  'drag-handle': () => W('<div style="display:flex;align-items:center;gap:6px;padding:6px 10px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:6px;cursor:grab"><div style="display:flex;flex-direction:column;gap:2px;opacity:0.4"><div style="display:flex;gap:2px"><div style="width:3px;height:3px;border-radius:50%;background:currentColor"></div><div style="width:3px;height:3px;border-radius:50%;background:currentColor"></div></div><div style="display:flex;gap:2px"><div style="width:3px;height:3px;border-radius:50%;background:currentColor"></div><div style="width:3px;height:3px;border-radius:50%;background:currentColor"></div></div></div><span style="font-size:11px">Drag me</span></div>'),
  'snap': () => W('<div style="position:relative;width:120px;height:40px;background:var(--color-surface-hover);border-radius:6px"><div style="position:absolute;left:50%;top:0;bottom:0;width:1px;background:#3b82f6;opacity:0.5"></div><div style="position:absolute;top:50%;left:0;right:0;height:1px;background:#3b82f6;opacity:0.5"></div><div style="position:absolute;left:calc(50% - 12px);top:calc(50% - 12px);width:24px;height:24px;background:#3b82f6;border-radius:4px;opacity:0.8"></div></div>'),

  // ── Game / 3D ──
  'hud': () => W('<div style="width:180px;height:60px;background:#0a0a0a;border-radius:6px;position:relative;overflow:hidden;padding:6px 8px"><div style="display:flex;justify-content:space-between"><div style="display:flex;align-items:center;gap:3px"><span style="color:#ef4444;font-size:10px">&hearts;</span><div style="width:50px;height:5px;background:#333;border-radius:3px"><div style="width:70%;height:100%;background:#ef4444;border-radius:3px"></div></div></div><span style="font-family:var(--font-mono);font-size:10px;color:#22c55e">Score: 1250</span></div><div style="position:absolute;bottom:6px;right:8px;width:20px;height:20px;border:1px solid rgba(255,255,255,0.2);border-radius:3px;display:flex;align-items:center;justify-content:center;font-size:7px;color:rgba(255,255,255,0.4)">MAP</div></div>'),
  'health-bar': () => W('<div style="display:flex;align-items:center;gap:4px"><span style="color:#ef4444;font-size:12px">&hearts;</span><div style="width:100px;height:8px;background:#333;border-radius:4px;overflow:hidden"><div style="width:65%;height:100%;background:linear-gradient(90deg,#ef4444,#f59e0b);border-radius:4px"></div></div><span style="font-family:var(--font-mono);font-size:10px;color:var(--color-text-tertiary)">65</span></div>'),
  'radial-menu': () => W(svg(80,80,'<circle cx="40" cy="40" r="30" fill="none" stroke="var(--color-border)" stroke-width="1"/><circle cx="40" cy="40" r="10" fill="#3b82f6"/>' + [[40,10],[65,25],[65,55],[40,70],[15,55],[15,25]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="7" fill="var(--color-surface-hover)" stroke="var(--color-border)" stroke-width="1"/>`).join(''))),
  'crosshair': () => W(svg(50,50,'<circle cx="25" cy="25" r="12" stroke="rgba(255,100,100,0.8)" fill="none" stroke-width="1.5"/><line x1="25" y1="10" x2="25" y2="40" stroke="rgba(255,100,100,0.5)" stroke-width="1"/><line x1="10" y1="25" x2="40" y2="25" stroke="rgba(255,100,100,0.5)" stroke-width="1"/><circle cx="25" cy="25" r="2" fill="rgba(255,100,100,0.8)"/>')),
  'inventory': () => W('<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:2px">'+['\u2694','\u2764','\u26A1','\u2B50','','','\u2696',''].map(e=>`<div style="width:24px;height:24px;background:#1a1d26;border:1px solid #3d4150;border-radius:3px;display:flex;align-items:center;justify-content:center;font-size:12px">${e}</div>`).join('')+'</div>'),
  'virtual-joystick': () => W(svg(60,60,'<circle cx="30" cy="30" r="25" fill="none" stroke="var(--color-border)" stroke-width="1.5"/><circle cx="35" cy="25" r="10" fill="rgba(59,130,246,0.3)" stroke="#3b82f6" stroke-width="1.5"/>')),

  // ── Mobile / Touch ──
  'tap': () => W(svg(50,50,'<circle cx="25" cy="25" r="8" fill="rgba(59,130,246,0.2)" stroke="#3b82f6" stroke-width="1.5"/><circle cx="25" cy="25" r="3" fill="#3b82f6"/>')),
  'swipe': () => W(svg(80,40,'<circle cx="20" cy="20" r="5" fill="rgba(59,130,246,0.3)"/><path d="M25 20 L55 20" stroke="#3b82f6" stroke-width="2"/><polyline points="50 15 55 20 50 25" stroke="#3b82f6" stroke-width="2"/>')),
  'pinch': () => W(svg(60,60,'<circle cx="18" cy="35" r="4" fill="rgba(59,130,246,0.3)" stroke="#3b82f6" stroke-width="1"/><circle cx="42" cy="25" r="4" fill="rgba(59,130,246,0.3)" stroke="#3b82f6" stroke-width="1"/><path d="M22 33 L26 31" stroke="#3b82f6" stroke-width="1" stroke-dasharray="2"/><path d="M38 27 L34 29" stroke="#3b82f6" stroke-width="1" stroke-dasharray="2"/>')),
  'bottom-navigation': () => W(`<div style="display:flex;justify-content:space-around;padding:6px 16px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:12px;min-width:180px"><div style="display:flex;flex-direction:column;align-items:center;gap:1px;color:#3b82f6;font-size:8px">${I.layers}<span style="font-weight:500">Home</span></div><div style="display:flex;flex-direction:column;align-items:center;gap:1px;color:var(--color-text-tertiary);font-size:8px">${I.search}<span>Find</span></div><div style="display:flex;flex-direction:column;align-items:center;gap:1px;color:var(--color-text-tertiary);font-size:8px">${I.bell}<span>Alert</span></div><div style="display:flex;flex-direction:column;align-items:center;gap:1px;color:var(--color-text-tertiary);font-size:8px">${I.user}<span>Me</span></div></div>`),
  'touch-target': () => W('<div style="position:relative;width:44px;height:44px;border:2px dashed rgba(59,130,246,0.3);border-radius:8px;display:flex;align-items:center;justify-content:center"><div style="width:24px;height:24px;background:#3b82f6;border-radius:4px"></div><span style="position:absolute;bottom:-14px;font-size:8px;color:var(--color-text-tertiary)">44px</span></div>'),
  'haptic-feedback': () => WS('gap:4px', '<div style="width:28px;height:28px;background:#3b82f6;border-radius:6px;animation:wiggle 0.5s ease infinite"></div><span style="font-size:10px;color:var(--color-text-tertiary)">buzz</span>'),
  'pull-to-refresh': () => W(svg(50,60,'<path d="M25 15 L25 40" stroke="#3b82f6" stroke-width="2"/><polyline points="18 22 25 15 32 22" stroke="#3b82f6" stroke-width="2"/><circle cx="25" cy="8" r="5" fill="none" stroke="#3b82f6" stroke-width="1.5" stroke-dasharray="15 5"/>')),
  'grabber': () => W('<div style="width:36px;height:4px;background:#d1d5db;border-radius:2px"></div>'),
  'safe-area': () => W('<div style="width:80px;height:60px;border:1.5px solid var(--color-border);border-radius:10px;position:relative;overflow:hidden"><div style="position:absolute;top:0;left:50%;transform:translateX(-50%);width:24px;height:6px;background:var(--color-border);border-radius:0 0 4px 4px"></div><div style="position:absolute;inset:8px 4px 10px;border:1px dashed rgba(59,130,246,0.3);border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:7px;color:#3b82f6">Safe</div><div style="position:absolute;bottom:2px;left:50%;transform:translateX(-50%);width:20px;height:3px;background:var(--color-border);border-radius:2px"></div></div>'),

  // ── Accessibility ──
  'accessibility-a11y': () => W('<div style="display:flex;align-items:center;gap:8px"><div style="width:36px;height:36px;border-radius:50%;background:#3b82f6;display:flex;align-items:center;justify-content:center;color:white;font-size:16px;font-weight:700">A</div><span style="font-size:11px;color:var(--color-text-secondary)">11y</span></div>'),
  'screen-reader': () => W(`<div style="display:flex;align-items:center;gap:6px;padding:6px 10px;background:var(--color-surface-hover);border-radius:6px;font-size:11px;color:var(--color-text-secondary)"><span style="color:#3b82f6">${I.eye}</span>"Submit Button"</div>`),
  'keyboard-navigation': () => WS('gap:4px', ['Tab','Enter','Esc'].map(k=>`<kbd style="padding:2px 8px;background:var(--color-surface);border:1px solid var(--color-border);border-radius:4px;font-size:10px;font-family:var(--font-mono);box-shadow:0 1px 0 var(--color-border)">${k}</kbd>`).join('')),
  'focus-trap': () => W('<div style="width:140px;padding:8px;border:2px solid #3b82f6;border-radius:8px;display:flex;flex-direction:column;gap:4px;position:relative"><div style="position:absolute;top:-8px;left:8px;background:var(--color-bg);padding:0 4px;font-size:9px;color:#3b82f6;font-weight:500">Focus Trap</div><input class="demo-input" style="width:100%;font-size:10px" value="Trapped focus" readonly><button class="demo-btn demo-btn-primary" style="padding:3px 8px;font-size:10px">OK</button></div>'),
  'contrast-ratio': () => WS('gap:8px', '<div style="padding:4px 10px;background:#1f2937;color:white;border-radius:4px;font-size:11px">AAA 12:1</div><div style="padding:4px 10px;background:#6b7280;color:white;border-radius:4px;font-size:11px">AA 4.5:1</div><div style="padding:4px 10px;background:#d1d5db;color:white;border-radius:4px;font-size:11px;opacity:0.6">Fail</div>'),
  'skip-link': () => W('<div style="padding:4px 10px;background:#3b82f6;color:white;border-radius:4px;font-size:11px;font-weight:500">Skip to main content</div>'),
  'alt-text': () => W(`<div style="display:flex;align-items:center;gap:6px;padding:6px;background:var(--color-surface-hover);border-radius:6px"><div style="width:32px;height:32px;background:var(--color-border);border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:12px">${I.eye}</div><span style="font-size:10px;color:var(--color-text-tertiary);font-style:italic">alt="A blue button"</span></div>`),
  'aria': () => W('<div style="font-family:var(--font-mono);font-size:10px;color:var(--color-text-secondary)"><span style="color:#8b5cf6">role</span>=<span style="color:#22c55e">"dialog"</span><br><span style="color:#8b5cf6">aria-label</span>=<span style="color:#22c55e">"Close"</span></div>'),
  'tabindex': () => WS('gap:4px', [1,2,3].map(n=>`<div style="width:32px;height:24px;border:1.5px solid ${n===2?'#3b82f6':'#d1d5db'};border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:10px;color:${n===2?'#3b82f6':'var(--color-text-tertiary)'};${n===2?'box-shadow:0 0 0 2px rgba(59,130,246,0.15)':''}">${n}</div>`).join('')),
  'semantic-html': () => W('<div style="font-family:var(--font-mono);font-size:10px;line-height:1.6"><span style="color:#8b5cf6">&lt;header&gt;</span><br><span style="color:#8b5cf6">&lt;main&gt;</span><br><span style="color:#8b5cf6">&lt;footer&gt;</span></div>'),
  'reduced-motion': () => W('<div style="display:flex;align-items:center;gap:6px;padding:6px 10px;background:var(--color-surface-hover);border-radius:6px;font-size:10px;color:var(--color-text-secondary)">prefers-reduced-motion</div>'),

  // ── Scroll / Position ──
  'scrollbar': () => W('<div style="width:120px;height:50px;border:1px solid var(--color-border);border-radius:6px;position:relative;overflow:hidden"><div style="position:absolute;right:2px;top:6px;width:4px;height:20px;background:#d1d5db;border-radius:2px"></div><div style="padding:6px;font-size:9px;color:var(--color-text-tertiary);line-height:1.5">Scrollable<br>content<br>here</div></div>'),
  'infinite-scroll': () => WS('flex-direction:column;gap:3px', [1,2,3].map(()=>'<div style="width:140px;height:14px;background:var(--color-surface-hover);border-radius:3px"></div>').join('')+'<div class="demo-spinner" style="width:16px;height:16px;border-width:2px;margin:4px auto 0"></div>'),
  'sticky-header': () => W('<div style="width:140px;height:60px;border:1px solid var(--color-border);border-radius:6px;overflow:hidden;position:relative"><div style="position:absolute;top:0;left:0;right:0;height:18px;background:var(--color-surface);border-bottom:1px solid var(--color-border);display:flex;align-items:center;padding:0 6px;font-size:8px;color:var(--color-text-tertiary);z-index:1;box-shadow:0 1px 3px rgba(0,0,0,0.05)">Sticky Header</div><div style="padding:22px 6px 6px;font-size:8px;color:var(--color-text-tertiary);line-height:1.6">Content scrolls<br>underneath the<br>sticky header</div></div>'),
  'scroll-snap': () => WS('gap:4px', [1,2,3].map(n=>`<div style="width:50px;height:36px;background:rgba(59,130,246,${n===2?0.2:0.08});border:1px solid rgba(59,130,246,${n===2?0.4:0.15});border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:10px;color:#3b82f6;${n===2?'transform:scale(1.05)':''}">${n}</div>`).join('')),
  'back-to-top': () => W(`<button class="demo-btn-icon" style="width:40px;height:40px;background:var(--color-surface);border:1px solid var(--color-border);box-shadow:var(--shadow-md)">${I.arrU}</button>`),
  'scroll-shadow': () => W('<div style="width:140px;height:40px;border:1px solid var(--color-border);border-radius:6px;position:relative;overflow:hidden"><div style="position:absolute;bottom:0;left:0;right:0;height:16px;background:linear-gradient(transparent,rgba(0,0,0,0.06))"></div><div style="padding:6px;font-size:9px;color:var(--color-text-tertiary)">Content...</div></div>'),
  'parallax': () => W('<div style="width:140px;height:50px;border-radius:6px;position:relative;overflow:hidden"><div style="position:absolute;inset:0;background:linear-gradient(135deg,#1e3a5f,#3b82f6)"></div><div style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center;color:white;font-size:11px">Parallax</div></div>'),

  // ── Loading / Progress ──
  'loader': () => W('<div class="demo-spinner"></div>'),
  'linear-progress': () => W('<div class="demo-progress" style="width:160px"><div class="demo-progress-bar" style="width:45%"></div></div>'),
  'circular-progress': () => W(svg(40,40,'<circle cx="20" cy="20" r="16" fill="none" stroke="#e5e7eb" stroke-width="3"/><circle cx="20" cy="20" r="16" fill="none" stroke="#3b82f6" stroke-width="3" stroke-dasharray="75 100" stroke-linecap="round" transform="rotate(-90 20 20)"/>')),
  'indeterminate-progress': () => W('<div style="width:160px;height:4px;background:#e5e7eb;border-radius:2px;overflow:hidden;position:relative"><div style="position:absolute;height:100%;background:#3b82f6;border-radius:2px;animation:progressIndeterminate 1.5s ease-in-out infinite"></div></div>'),
  'inline-loading': () => W('<button class="demo-btn demo-btn-primary" style="display:flex;align-items:center;gap:6px"><span class="demo-spinner" style="width:14px;height:14px;border-width:2px;border-color:rgba(255,255,255,0.3);border-top-color:white"></span>Saving...</button>'),
  'save-indicator': () => WS('gap:6px', `<span style="color:#22c55e">${I.checkC}</span><span style="font-size:11px;color:var(--color-text-tertiary)">Saved</span>`),
  'connection-status': () => WS('gap:6px', '<div style="width:8px;height:8px;border-radius:50%;background:#22c55e"></div><span style="font-size:11px;color:var(--color-text-secondary)">Connected</span>'),
  'offline-banner': () => W('<div style="width:180px;padding:6px 10px;background:#fef3c7;border:1px solid #fde68a;border-radius:6px;font-size:10px;color:#92400e;text-align:center">You are offline</div>'),
  'retry-button': () => W('<div style="display:flex;flex-direction:column;align-items:center;gap:6px"><span style="font-size:11px;color:var(--color-text-tertiary)">Failed to load</span><button class="demo-btn demo-btn-secondary" style="padding:4px 12px;font-size:11px">Retry</button></div>'),

  // ── Search / Filter ──
  'search': () => W(`<div style="position:relative;display:inline-flex;align-items:center"><span style="position:absolute;left:10px;color:#9ca3af">${I.search}</span><input class="demo-input" style="padding-left:32px;width:180px" placeholder="Search..." readonly></div>`),
  'search-box': () => W(`<div style="position:relative;display:inline-flex;align-items:center"><span style="position:absolute;left:10px;color:#9ca3af">${I.search}</span><input class="demo-input" style="padding-left:32px;width:160px" placeholder="Search..." readonly></div>`),
  'filter-chip': () => WS('gap:4px', `<span class="demo-chip">Category <span style="cursor:pointer">${I.close}</span></span><span class="demo-chip" style="background:#fef3c7;color:#d97706;border-color:#fde68a">Price <span style="cursor:pointer">${I.close}</span></span>`),
  'filter-panel': () => WS('flex-direction:column;align-items:flex-start;gap:6px', `<span style="font-size:11px;font-weight:600">Filters</span><label class="demo-checkbox checked" style="font-size:10px" data-demo-toggle="checkbox"><span class="demo-checkbox-box" style="width:14px;height:14px"><span class="demo-checkbox-check">${I.check}</span></span><span>In Stock</span></label><label class="demo-checkbox" style="font-size:10px" data-demo-toggle="checkbox"><span class="demo-checkbox-box" style="width:14px;height:14px"><span class="demo-checkbox-check">${I.check}</span></span><span>On Sale</span></label>`),
  'sort-control': () => W(`<div class="demo-dropdown-mini" data-demo-toggle="dropdown"><div class="demo-dropdown-trigger" style="font-size:11px">Sort by: Date ${I.chev}</div><div class="demo-dropdown-list"><div class="demo-dropdown-option">Date</div><div class="demo-dropdown-option">Name</div><div class="demo-dropdown-option">Price</div></div></div>`),
  'no-results-state': () => W(`<div style="display:flex;flex-direction:column;align-items:center;gap:6px;padding:10px"><span style="color:var(--color-text-tertiary)">${I.search}</span><span style="font-size:11px;color:var(--color-text-tertiary)">No results for "xyz"</span></div>`),
  'query-builder': () => W('<div style="display:flex;align-items:center;gap:4px;font-size:10px;flex-wrap:wrap"><span class="demo-chip" style="font-size:10px;padding:2px 6px">status = active</span><span style="color:var(--color-text-tertiary)">AND</span><span class="demo-chip" style="font-size:10px;padding:2px 6px">role = admin</span></div>'),

  // ── Collapse / Expand ──
  'details-summary': () => W(`<div style="width:180px"><div style="display:flex;align-items:center;gap:6px;padding:6px;cursor:pointer;font-size:12px;font-weight:500"><span style="color:#3b82f6;transform:rotate(90deg);display:inline-flex">${ico('<polyline points="6 4 10 8 6 12"/>')}</span>Details</div><div style="padding:0 6px 6px 28px;font-size:10px;color:var(--color-text-tertiary)">Content revealed</div></div>`),
  'show-more': () => W('<div style="display:flex;flex-direction:column;align-items:center;gap:4px"><div style="width:140px;height:20px;overflow:hidden;font-size:10px;color:var(--color-text-tertiary)">Long text content that is truncated...</div><button style="font-size:10px;color:#3b82f6;background:none;border:none;cursor:pointer;font-weight:500">Show more</button></div>'),
  'chevron': () => WS('gap:8px', `<span style="color:var(--color-text-tertiary)">${I.chev}</span><span style="color:var(--color-text-tertiary);transform:rotate(-90deg);display:inline-flex">${I.chev}</span><span style="color:var(--color-text-tertiary);transform:rotate(90deg);display:inline-flex">${I.chev}</span><span style="color:var(--color-text-tertiary);transform:rotate(180deg);display:inline-flex">${I.chev}</span>`),
  'progressive-disclosure': () => WS('flex-direction:column;gap:4px;width:160px', '<div style="padding:4px 8px;background:var(--color-surface-hover);border-radius:4px;font-size:10px">Basic info shown</div><div style="padding:4px 8px;border:1px dashed var(--color-border);border-radius:4px;font-size:10px;color:var(--color-text-tertiary);text-align:center">+ More details</div>'),
  'clamp': () => W('<div style="width:140px;font-size:10px;color:var(--color-text-secondary);display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden">This text is clamped to two lines. Extra content will be hidden with ellipsis at the end.</div>'),

  // ── Implementation / Frontend ──
  'component-library': () => WS('gap:4px', '<button class="demo-btn demo-btn-primary" style="padding:3px 8px;font-size:10px">Btn</button><span class="demo-chip" style="font-size:9px;padding:1px 6px">Tag</span><div style="width:16px;height:16px;border-radius:50%;background:#3b82f6"></div><input class="demo-input" style="width:50px;padding:3px 6px;font-size:9px" value="Input" readonly>'),
  'headless-ui': () => W('<div style="font-family:var(--font-mono);font-size:10px;padding:8px;background:var(--color-surface-hover);border-radius:6px;color:var(--color-text-secondary)"><span style="color:#8b5cf6">Headless</span>: behavior only<br>style = <span style="color:#22c55e">you decide</span></div>'),
  'variant': () => WS('gap:4px', '<button class="demo-btn demo-btn-primary" style="padding:3px 8px;font-size:10px">primary</button><button class="demo-btn demo-btn-secondary" style="padding:3px 8px;font-size:10px">secondary</button><button class="demo-btn demo-btn-ghost" style="padding:3px 8px;font-size:10px">ghost</button>'),
  'size-variant': () => WS('gap:4px;align-items:center', '<button class="demo-btn demo-btn-primary" style="padding:2px 6px;font-size:9px">S</button><button class="demo-btn demo-btn-primary" style="padding:4px 10px;font-size:11px">M</button><button class="demo-btn demo-btn-primary" style="padding:6px 14px;font-size:13px">L</button>'),
  'breakpoint': () => WS('gap:4px;font-family:var(--font-mono);font-size:9px', [{w:20,l:'sm'},{w:28,l:'md'},{w:40,l:'lg'},{w:50,l:'xl'}].map(({w,l})=>`<div style="width:${w}px;height:20px;background:rgba(59,130,246,0.1);border:1px solid rgba(59,130,246,0.2);border-radius:3px;display:flex;align-items:center;justify-content:center;color:#3b82f6">${l}</div>`).join('')),
  'z-index': () => W('<div style="position:relative;width:100px;height:50px"><div style="position:absolute;top:0;left:0;width:50px;height:30px;background:rgba(59,130,246,0.3);border:1px solid rgba(59,130,246,0.5);border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:8px;color:#3b82f6">z:1</div><div style="position:absolute;top:10px;left:20px;width:50px;height:30px;background:rgba(139,92,246,0.3);border:1px solid rgba(139,92,246,0.5);border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:8px;color:#8b5cf6">z:2</div></div>'),
  'portal': () => W('<div style="display:flex;align-items:center;gap:8px"><div style="width:60px;height:36px;border:1px solid var(--color-border);border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:8px;color:var(--color-text-tertiary)">App</div><span style="font-size:12px;color:var(--color-text-tertiary)">\u2192</span><div style="width:40px;height:28px;border:1px dashed #3b82f6;border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:8px;color:#3b82f6">Portal</div></div>'),
  'lazy-loading': () => WS('gap:4px', '<div style="width:40px;height:40px;background:var(--color-surface-hover);border-radius:4px;display:flex;align-items:center;justify-content:center"><div class="demo-spinner" style="width:14px;height:14px;border-width:2px"></div></div><span style="font-size:10px;color:var(--color-text-tertiary)">Loading on demand</span>'),
  'virtualization': () => WS('flex-direction:column;gap:1px', '<div style="width:140px;height:4px;background:var(--color-border-subtle);border-radius:1px;opacity:0.3"></div><div style="width:140px;height:4px;background:var(--color-border-subtle);border-radius:1px;opacity:0.3"></div><div style="width:140px;height:12px;background:rgba(59,130,246,0.12);border:1px solid rgba(59,130,246,0.2);border-radius:2px;display:flex;align-items:center;justify-content:center;font-size:7px;color:#3b82f6">viewport</div><div style="width:140px;height:4px;background:var(--color-border-subtle);border-radius:1px;opacity:0.3"></div><div style="width:140px;height:4px;background:var(--color-border-subtle);border-radius:1px;opacity:0.3"></div>'),
  'ssr': () => W('<div style="font-family:var(--font-mono);font-size:10px"><span style="color:#8b5cf6">Server</span> \u2192 HTML \u2192 <span style="color:#f59e0b">Client</span></div>'),
  'bem': () => W('<div style="font-family:var(--font-mono);font-size:10px;line-height:1.6;color:var(--color-text-secondary)">.block<br>.block__element<br>.block--modifier</div>'),

  // ── Legacy ──
  'marquee': () => W('<div style="width:150px;overflow:hidden;font-size:11px;color:var(--color-text-tertiary);border:1px dashed var(--color-border);border-radius:4px;padding:4px"><div style="animation:easeInDemo 3s linear infinite;white-space:nowrap">Scrolling text \u2192\u2192\u2192</div></div>'),
  'splash-screen': () => W('<div style="width:80px;height:60px;background:linear-gradient(135deg,#1e3a5f,#3b82f6);border-radius:8px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px"><div style="width:20px;height:20px;background:white;border-radius:6px;opacity:0.9"></div><div class="demo-spinner" style="width:12px;height:12px;border-width:1.5px;border-color:rgba(255,255,255,0.3);border-top-color:white"></div></div>'),
  'wizard': () => { const steps = [1,2,3].map((n,i)=>{const bg=i<=1?'#3b82f6':'#d1d5db';const c=i<=1?'white':'#6b7280';const line=i<2?`<div style="width:20px;height:2px;background:${i===0?'#3b82f6':'#d1d5db'}"></div>`:'' ;return `<div style="width:20px;height:20px;border-radius:50%;background:${bg};color:${c};display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:600">${n}</div>${line}`}).join(''); return WS('gap:0',steps) },
  'splitter': () => W('<div style="display:flex;width:140px;height:40px;border:1px solid var(--color-border);border-radius:6px;overflow:hidden"><div style="flex:1;display:flex;align-items:center;justify-content:center;font-size:9px;color:var(--color-text-tertiary)">A</div><div style="width:6px;background:var(--color-surface-hover);cursor:col-resize;display:flex;align-items:center;justify-content:center"><div style="display:flex;flex-direction:column;gap:2px"><div style="width:2px;height:2px;border-radius:50%;background:var(--color-text-tertiary)"></div><div style="width:2px;height:2px;border-radius:50%;background:var(--color-text-tertiary)"></div><div style="width:2px;height:2px;border-radius:50%;background:var(--color-text-tertiary)"></div></div></div><div style="flex:1;display:flex;align-items:center;justify-content:center;font-size:9px;color:var(--color-text-tertiary)">B</div></div>'),
  'system-tray': () => WS('gap:6px;padding:4px 8px;background:var(--color-surface-hover);border-radius:4px', `<span style="color:var(--color-text-tertiary);font-size:12px">${I.bell}</span><span style="color:var(--color-text-tertiary);font-size:12px">${I.gear}</span><span style="font-size:10px;color:var(--color-text-tertiary)">9:41</span>`),
})


/* ── Public API ──────────────────────────────────────────────── */

/* ── Merged registry ─────────────────────────────────────────── */
const allDemos = Object.freeze({ ...specific, ...extras1, ...extras2, ...extras3, ...extras4 })

/**
 * Check whether a term has a visual demo.
 * @param {string} termId - The slugified term ID
 * @returns {boolean}
 */
export const hasDemo = (termId) => typeof allDemos[termId] === 'function'

/**
 * Get demo HTML for a given term.
 * @param {string} termId - The slugified term ID
 * @returns {string} HTML string
 */
export const getDemoHTML = (termId) => {
  const builder = allDemos[termId]
  return typeof builder === 'function' ? builder() : ''
}

/**
 * Set up delegated click handlers for interactive demos.
 */
export const initDemoInteractions = () => {
  const handleClick = (event) => {
    const { target } = event
    const sw = target.closest('[data-demo-toggle="switch"]')
    if (sw) { sw.classList.toggle('on'); const lb = sw.nextElementSibling; if (lb && lb.tagName !== 'BUTTON') lb.textContent = sw.classList.contains('on') ? 'ON' : 'OFF'; return }
    const cb = target.closest('[data-demo-toggle="checkbox"]')
    if (cb) { cb.classList.toggle('checked'); const sp = cb.querySelector('span:last-child'); if (sp) sp.textContent = cb.classList.contains('checked') ? 'Checked' : 'Unchecked'; return }
    const rd = target.closest('[data-demo-toggle="radio"]')
    if (rd) { const g = rd.closest('[data-demo-radio-group]'); if (g) g.querySelectorAll('[data-demo-toggle="radio"]').forEach(r => r.classList.remove('selected')); rd.classList.add('selected'); return }
    const ah = target.closest('.demo-accordion-header')
    if (ah) { const item = ah.closest('.demo-accordion-item'); if (item) item.classList.toggle('open'); return }
    const dd = target.closest('[data-demo-toggle="dropdown"]')
    if (dd) { const opt = target.closest('.demo-dropdown-option'); if (opt) { const tr = dd.querySelector('.demo-dropdown-trigger'); if (tr) tr.innerHTML = `${opt.textContent} ${I.chev}`; dd.classList.remove('open'); return } const tr = target.closest('.demo-dropdown-trigger'); if (tr) dd.classList.toggle('open'); return }
    document.querySelectorAll('.demo-dropdown-mini.open').forEach(d => { if (!d.contains(target)) d.classList.remove('open') })
  }
  document.addEventListener('click', handleClick)
}
